version: "3.1"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: $MONGO_WEB_USERNAME
      ME_CONFIG_BASICAUTH_PASSWORD: $MONGO_WEB_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@mongo:27017/

  aw-project:
    build: .
    image: aw-project
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@mongo:27017/
      PORT: 3000
      LOCALTUNNEL_SUBDOMAIN: $LOCALTUNNEL_SUBDOMAIN
      LOCALTUNNEL_ENABLED: $LOCALTUNNEL_ENABLED
    depends_on:
      - mongo
      - mongo-express

volumes:
  mongodb:
